# AUTO-GENERATED by src.configs.generate — do not edit manually
# Regenerate: python -m src.configs.generate

class Application:
    name: str
    version: str
    debug: bool
    environment: str

application: Application

class Database:
    url: str
    pool_size: int
    max_overflow: int
    pool_timeout: int
    echo: bool
    pool_pre_ping: bool
    pool_recycle: int

database: Database

class Security:
    class Jwt:
        secret_key: str
        algorithm: str
        access_token_expire_minutes: int
        refresh_token_expire_days: int
    jwt: Jwt
    class Admin:
        email: str
        username: str
        first_name: str
        last_name: str
        password: str
    admin: Admin
    class Password:
        bcrypt_rounds: int
    password: Password
    token_cleanup_interval_seconds: int
    extension_token_expire_days: int
    extension_token_cleanup_interval_seconds: int

security: Security

class Server:
    class Cors:
        origins: list[str]
        allow_credentials: bool
        allow_methods: list[str]
        allow_headers: list[str]
    cors: Cors
    class RateLimit:
        enabled: bool
        login: str
        register: str
        refresh: str
        predict: str
        predict_batch: str
        extension_register: str
        extension_renew: str
        extension_predict: str
    rate_limit: RateLimit

server: Server

class Logging:
    level: str
    format: str
    file_path: str

logging: Logging

class Inference:
    models_dir: str
    calibrator_path: str
    decision_threshold: float
    alert_threshold: float
    class Emails:
        max_body_bytes: int
    emails: Emails
    class Review:
        low_threshold: float
        high_threshold: float
    review: Review
    class Drift:
        log_path: str
        fpr_threshold: float
    drift: Drift
    class AutoReviewer:
        provider: str
        api_key: str
        model_name: str
        timeout_seconds: float
        max_retries: int
        cache_enabled: bool
        cache_ttl_seconds: int
        cache_max_size: int
    auto_reviewer: AutoReviewer
    class Batch:
        max_emails_per_request: int
    batch: Batch
    class Shadow:
        enabled: bool
        days: int
    shadow: Shadow
    class Explain:
        tfidf_topk_enabled: bool
        tfidf_topk: int
    explain: Explain
    class Upload:
        require_signature: bool
        hmac_secret: str
        pickle_sandbox_enabled: bool
        pickle_sandbox_timeout_seconds: float
    upload: Upload

inference: Inference

class Training:
    min_batch_size: int
    min_per_class: int
    require_balance_delta: float
    holdout_path: str
    csv_max_bytes: int
    csv_max_rows: int
    max_iter_per_call: int
    class QualityGate:
        enabled: bool
        max_oov_rate: float
    quality_gate: QualityGate

training: Training

class Review:
    assignment_strategy: str
    auto_review_batch_max: int
    sla_seconds: int
    class RejectionSampler:
        enabled: bool
        sample_rate: float
        policy: str
    rejection_sampler: RejectionSampler
    class DisagreementLog:
        enabled: bool
    disagreement_log: DisagreementLog

review: Review

class Benchmark:
    csv_max_bytes: int
    csv_max_rows: int
    max_versions_per_run: int
    ece_num_bins: int

benchmark: Benchmark

class Sse:
    heartbeat_seconds: float
    subscriber_queue_max: int
    replay_window_size: int
    echo_enabled: bool

sse: Sse

class Extension:
    cors_origins: list[str]
    allowlist_domains: list[str]
    allowlist_emails: list[str]
    blocklist_domains: list[str]
    blocklist_emails: list[str]
    class GoogleOauth:
        client_id: str
    google_oauth: GoogleOauth

extension: Extension

def reload_config() -> None: ...
